###
POST htpp://localhost:4000/sendMail
Content-Type: application/json

{

    "emailFrom":"doudou6500@gmail.com",
    "emailTo":"doudou6500@gmail.com",
    "subject":"Hello Everybody",
    "message":"BlaBlabla ",
    "html":"<b>BlaBlabla</b>"
}