Get http://localhost:4000/skills

####

GET http://localhost:4000/5f19940f-6ff5-4642-842e-cfebb608327b

####
POST http://localhost:4000/skills
Content-Type: application/json

{
    "name":"Github",
    "description":"Lorem Ipsum lorem ipsum",
    "logo":"https://img2.freepng.fr/20180331/udw/kisspng-social-media-github-computer-icons-logo-github-5ac0188083c4f5.8572681115225386245397.jpg"
}

###
PUT http://localhost:4000/contact/37b94ec2-52bb-4ff7-b7c4-b41219b16c2b
Content-Type: application/json

{
    "name" : "Linkedin",
    "link" : "https://www.linkedin.com/in/marion-hourdou/",
    "logo": "https://png.pngtree.com/element_our/sm/20180626/sm_5b32227feb591.jpg"
}

###
DELETE http://localhost:4000/contact/647184b0-bb98-4eff-9422-27a07f506777
